name: mad_music
description: "An open source music player which allows you to stream playlists from youtube, soptify and local mp3 files"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  audioplayers: ^6.0.0
  file_picker: ^10.2.0
  path_provider: ^2.0.11
  path: any
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  uuid: ^4.4.0
  flutter_launcher_icons: ^0.14.4
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  youtube_explode_dart: ^2.1.0
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - .env
